#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'robotic-project','console_scripts','kudur2'
__requires__ = 'robotic-project'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('robotic-project', 'console_scripts', 'kudur2')()
    )
