#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'a2','console_scripts','waypoint_follower'
__requires__ = 'a2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('a2', 'console_scripts', 'waypoint_follower')()
    )
